[package]
name = "solar-system"
version = "0.2.0"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[dependencies]
bevy = "0.14"
bevy_framepace = "0.17"
bevy_mod_billboard = "0.7"
nalgebra = "0.33"
strum = { version="0.26", features = ["derive"] }
uom = "0.36"
