[package]
name = "solar-system"
version = "0.1.0"
edition = "2021"

[features]
wasm = ["dep:console_error_panic_hook", "dep:wasm-bindgen"]

[dependencies]
kiss3d = "0.35.0"
nalgebra = "0.30.1"
console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen = { version = "0.2.83", optional = true }
